## Ejercicios

1. Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\InvitadoLaptop\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
array_randint_bi = np.random.randint(34, 98, (4,3))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi} \n")

El array bidimensional creado a partir del método np.random.randint(): 
  [[85 58 45]
 [77 62 74]
 [77 56 87]
 [89 80 62]] 



2. Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

Las listas para crear los arrays son las siguientes:

In [5]:
lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

In [6]:
array_unidimensional = np.array(lista1)
print(f"El array unidimensional creado a partir de la lista es: \n  {array_unidimensional} \n")

El array unidimensional creado a partir de la lista es: 
  [34 56 71 98 10] 



In [7]:
array_bidimensional = np.array(lista2)
print(f"El array bidimensional creado a partir de la lista es:\n  {array_bidimensional}\n")

El array bidimensional creado a partir de la lista es:
  [[23 45 89 56]
 [12 43 82 44]]



3. Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:

El primer elemento.

**Lo elementos que están en posición impar.

**Los cuatro primeros elementos.

**Los últimos tres elementos.

**Los elementos entre el 4 y el 8 (incluido).

In [10]:
array_unidimensional_arange =  np.arange(1,51)
print(f"El array bidimensional creado a partir del método np.emtpy(): \n  {array_unidimensional_arange} \n")

El array bidimensional creado a partir del método np.emtpy(): 
  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 



In [16]:
print(f"Lo elementos que están en posición impar: \n {array_unidimensional_arange[0:51:2]}")

Lo elementos que están en posición impar: 
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [ ]:
print(f"Los cuatro primeros elementos: \n {array_unidimensional_arange[:4]}")

Los tres últimos elementos de nuestro array son: 
 [1 2 3 4]


In [11]:
print(f"Los tres últimos elementos de nuestro array son: \n {array_unidimensional_arange[-3:]}")

Los tres últimos elementos de nuestro array son: 
 [48 49 50]


In [ ]:
print(f"Los elementos entre el 4 y el 8 (incluido): \n {array_unidimensional_arange[4:8]}")

El tercer y cuarto elemento de nuestro array son: 
 [5 6 7 8]


4. Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

**La primera fila y todas las columnas.

**Todas las filas pares.

**La primera columna y todas las filas.

In [104]:
array_randint_bi = np.random.randint(0, 21, (4,5))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi} \n")

El array bidimensional creado a partir del método np.random.randint(): 
  [[ 1 15  6  1 12]
 [ 6 10 15 17 19]
 [ 0 13  4  2 18]
 [16  4 14 13  8]] 



In [105]:
print(f"La primera fila y todas las columnas: \n {array_randint_bi[0]}")

La primera fila y todas las columnas: 
 [ 1 15  6  1 12]


In [106]:
filas_pares = array_randint_bi[::2]
print(f"Todas las filas pares: \n  {filas_pares} \n")

Todas las filas pares: 
  [[ 1 15  6  1 12]
 [ 0 13  4  2 18]] 



In [107]:
print(f"La primera columna y todas las filas: \n {array_randint_bi[:4,0:1]}")

La primera columna y todas las filas: 
 [[ 1]
 [ 6]
 [ 0]
 [16]]


5. Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

**Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

**Los valores de mi array bidimensional multiplicalos por el escalar 10.

In [110]:
array_randint_bi = np.random.randint(0, 50, (4,5))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi} \n")

El array bidimensional creado a partir del método np.random.randint(): 
  [[30 24 45 32 36]
 [31 13 18 29 13]
 [37 27 47 32 36]
 [35 46 42 37  2]] 



In [111]:
print(f"Primer paso: creación de una máscara booleana \n {array_randint_bi > 30}")

print("-----------------------------")
print(f"Segundo paso: aplicar la máscara booleana \n {array_randint_bi[array_randint_bi > 30]}")


Primer paso: creación de una máscara booleana 
 [[False False  True  True  True]
 [ True False False False False]
 [ True False  True  True  True]
 [ True  True  True  True False]]
-----------------------------
Segundo paso: aplicar la máscara booleana 
 [45 32 36 31 37 47 32 36 35 46 42 37]


In [112]:
resultado_filtradoI = array_randint_bi[(array_randint_bi > 30) |  (array_randint_bi < 10)]
print(f"Objetivo: \n {resultado_filtradoI}")

Objetivo: 
 [45 32 36 31 37 47 32 36 35 46 42 37  2]


In [113]:
escalar = 10

multiplicacion_escalar = array_randint_bi * escalar

print("El resultado de la multiplicación del array con el escalar es:\n", multiplicacion_escalar)

El resultado de la multiplicación del array con el escalar es:
 [[300 240 450 320 360]
 [310 130 180 290 130]
 [370 270 470 320 360]
 [350 460 420 370  20]]


6. Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

**Suma el primer array con el segundo.

**Aplicar la potencia para el primer array elevado al segundo.

In [117]:
array_randint_bi2 = np.random.randint(50, 101, (4,5))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi2} \n")

El array bidimensional creado a partir del método np.random.randint(): 
  [[68 55 81 66 67]
 [75 79 78 88 96]
 [51 89 80 50 92]
 [83 99 99 57 77]] 



In [118]:
suma = np.add(array_randint_bi, array_randint_bi2)  # Suma los elementos correspondientes de los dos arrays
print("El resultado de la suma de los dos arrays es:\n", suma)


El resultado de la suma de los dos arrays es:
 [[ 98  79 126  98 103]
 [106  92  96 117 109]
 [ 88 116 127  82 128]
 [118 145 141  94  79]]


In [119]:
elevado = np.power(array_randint_bi, array_randint_bi2)  # Elevar los elementos correspondientes de los dos arrays
print("El resultado de la potencia de los dos arrays es:\n", elevado)

El resultado de la potencia de los dos arrays es:
 [[          0           0 -1056987539           0           0]
 [ 1108815199  1300916485           0  -787223327 -1906587263]
 [-1051634147   798879739   832964865           0           0]
 [-1798726597           0           0  -452002619           0]]


7. Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

Calcula:

**La media de los elementos

**La media de las columnas y redondéalo a dos decimales

**El valor máximo de cada fila

**El valor mínimo de cada fila

**Hay algun valor que sea mayor que 90 en tu array

**Donde los podemos encontrar, cuáles son sus índices

**Ordena el array de mayor a menor

In [120]:
array_randint_bi3 = np.random.randint(0, 100, (4,5))
print(f"El array bidimensional creado a partir del método np.random.randint(): \n  {array_randint_bi3} \n")

El array bidimensional creado a partir del método np.random.randint(): 
  [[92  0 94 34 26]
 [14 98 15 10 10]
 [30 95 68 90 78]
 [85 46 15 10 84]] 



In [122]:
media = np.mean(array_randint_bi3)

print(f"El cálculo de la media de todos los elementos del array es: \n {media}")

El cálculo de la media de todos los elementos del array es: 
 49.7


In [127]:
media_col = np.mean(array_randint_bi3, axis = 0) # noten que agregamos un eje donde aplico la funcion

print(f"La media de cada COLUMNA (axis = 0) del array es: \n {media_col}")

La media de cada COLUMNA (axis = 0) del array es: 
 [55.25 59.75 48.   36.   49.5 ]


In [128]:
maximo_fila = np.max(array_randint_bi3, axis = 1) # noten que agregamos un eje donde aplico la funcion

print(f"El valor máximo de cada FILA (axis = 1) del array es: \n {maximo_fila}")

El valor máximo de cada FILA (axis = 1) del array es: 
 [94 98 95 85]


In [129]:
minimo_fila = np.min(array_randint_bi3, axis = 1) # noten que agregamos un eje donde aplico la funcion

print(f"El valor mínimo de cada FILA (axis = 1) del array es: \n {minimo_fila}")

El valor mínimo de cada FILA (axis = 1) del array es: 
 [ 0 10 30 10]


In [131]:
resultado_where = np.where(array_randint_bi3 > 89)

print("El resultado del np.where() es: \n", resultado_where)

El resultado del np.where() es: 
 (array([0, 0, 1, 2, 2]), array([0, 2, 1, 1, 3]))


In [134]:
resultado_filtradoI = array_randint_bi3[(array_randint_bi3 > 90)]
print(f"El resultado del filtrado es: \n {resultado_filtradoI}")

El resultado del filtrado es: 
 [92 94 98 95]


In [135]:
print(f"Ordena el array de mayor a menor{-np.sort(-array_randint_bi3)}")

Ordena el array de mayor a menor[[94 92 34 26  0]
 [98 15 14 10 10]
 [95 90 78 68 30]
 [85 84 46 15 10]]
